input_features:
    -
        name: nch
        type: text
        encoder: rnn
        cell_type: lstm
        representation: sparse

output_features:
    -
        name: sop
        type: text

training:
    batch_size: 96
    epochs: 1000
    early_stop: 100
