input_features:
    -
        name: sop
        type: text
    -
        name: alt
        type: text
    -
        name: ten
        type: text

output_features:
    -
        name: bas
        type: text

training:
    batch_size: 96
