preprocessing:
    text:
        format: space

input_features:
    -
        name: sop
        type: text
        encoder: rnn
        cell_type: lstm

output_features:
    -
        name: alt
        type: text
        decoder: generator
        cell_type: lstm

training:
    batch_size: 96
    epochs: 1000
    early_stop: 10
